services:
  pulsarr:
    image: lakker/pulsarr:latest
    container_name: minerva-pulsarr
    ports:
      - "3003:3003"
    volumes:
      - ./volume1/docker/minerva-pulsarr:/app/data
      - .env:/app/.env
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
